### ISSUE TITLE
Sorting is not working

### ISSUE THREAD

**Issue by vmans** [t3brightside/pagelist#17]
In the latest versions, it seems sorting does not work.

Sort by has no effect. It's always the page uid that sets the sort order.

**Comment by t3brightside** [comment]
Hey, thanks. Just tested 'Pagelist: subapges' all sorting.options seem to work just fine, can't confirm it now.

**Comment by vmans** [comment]
Alphabetical does work, but Pagetree does not.

**Comment by t3brightside** [comment]
Tried but can not reproduce that issue...all sorting options work fine as tested now.

**Comment by vmans** [comment]
Tested it again and "Sort by Page tree (default)" is definitively following the _page uid_ sort ordering.

Perhaps it's due to the case that I use a category filter for pages over multiple page levels?

In this case, I expect the sort ordering to comply with the placing in the page tree. Perhaps my assumption is wrong?

**Comment by t3brightside** [comment]
Tested that, too can't recreate the problem now, works fine with cat filter or not. Must be something else...
Besides if shown pages are in different subsections it's parent page sorting field is not considered. It's only every pages individual sorting field is counted... To make parent page position to count would need a whole different approach.

Feel free to open the issue again if the issue is present with pages from the same subsection on same level and on a clean TYPO3 install.
